POST https://d512oay8u6.execute-api.us-east-1.amazonaws.com/dev/characters
Content-Type: application/json

{
  "nombre": "star wars",
  "altura": "1.80m",
  "masa": "80kg",
  "genero": "hombre"
}

###
GET https://d512oay8u6.execute-api.us-east-1.amazonaws.com/dev/starwars/12

###
GET https://d512oay8u6.execute-api.us-east-1.amazonaws.com/dev/characters

### Local Endpoints
POST http://localhost:3000/devcharacters
Content-Type: application/json

{
  "nombre": "Luke",
  "altura": "1.80m",
  "masa": "80kg",
  "genero": "mujer"
}
###
GET http://localhost:3000/dev/characters
###
GET http://localhost:3000/dev/starwars/12